[project]
name = "videre"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.24.0",
    "elevenlabs>=2.22.0",
    "anthropic>=0.72.0",
    "boto3>=1.40.69",
]
